<?xml version="1.0"?>
<robot name="tether" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- tether -->
<xacro:property name="tether_radius" value="0.001" />
<!-- <xacro:property name="tether_length" value="0.01155" /> -->S
<xacro:property name="tether_length" value="0.022" />
<xacro:property name="tether_mass" value="0.001" /> <!-- in kg-->
<xacro:property name="min_radius" value="0.001" />
<xacro:property name="min_length" value="0.0001" />
<xacro:property name="min_mass" value="0.00001" />

<xacro:property name="M_PI" value="3.1415926535897931" />

<!--
<xacro:property name="base_x_origin_to_tether_origin" value="0.060" />
<xacro:property name="base_y_origin_to_tether_origin" value="0.0" />
<xacro:property name="base_z_origin_to_tether_origin" value="0.0" /> -->


<xacro:macro name="cylinder_inertia" params="m r h">
<inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
izz="${m*r*r/2}" />
</xacro:macro>

<xacro:macro name="box_inertia" params="m x y z">
<inertia  ixx="${m*(y*y+z*z)/12.}" ixy = "0." ixz = "0."
iyy="${m*(x*x+z*z)/12.}" iyz = "0."
izz="${m*(x*x+z*z)/12.}" />
</xacro:macro>



<xacro:macro name="tether" params="tethernum parent tether_origin">
<!--fb : front, back ; lr: left, right -->
<!--
<link name="${tethernum}_min_link1">
<visual>
<origin xyz="-${min_length/2} 0 0" rpy="0 ${M_PI/2} 0" />
<geometry>
<cylinder radius="${min_radius}" length="${min_length}" />
</geometry>
<material name="DarkGray" />
</visual>
<collision>
<origin xyz="-${min_length/2} 0 0" rpy="0 ${M_PI/2} 0" />
<geometry>
<cylinder radius="${min_radius}" length="${min_length}" />
</geometry>
</collision>
<inertial>
<mass value="${min_mass}" />
<origin xyz="0 0 0" />
<cylinder_inertia  m="${min_mass}" r="${min_radius}" h="${min_length}" />
</inertial>
</link>
-->

<link name="${tethernum}_base_link1">
<visual>
<origin xyz="-${0.011/2} 0 ${tether_radius}" rpy="0 ${M_PI/2} 0" />
<geometry>
<cylinder radius="${tether_radius}" length="0.011" />
</geometry>
<material name="DarkGray" />
</visual>
<collision>
<origin xyz="-${0.011/2} 0.03 ${tether_radius}" rpy="0 ${M_PI/2} 0" />
<geometry>
<cylinder radius="${tether_radius}" length="0.011" />
</geometry>
</collision>
<inertial>
<mass value="${tether_mass}" />
<origin xyz="-0.003 0 0" />
<cylinder_inertia  m="${tether_mass}" r="${tether_radius}" h="0.011" />
</inertial>
</link>




<joint name="${tethernum}_joint1_1" type="fixed">
    <parent link="${parent}"/>
    <child link="${tethernum}_base_link1"/>
    <axis xyz="0 0 1" />
    <origin xyz="0 0.06 0.01" rpy="0 0 0" />
    <joint_properties damping="0" friction="0"/>
</joint>


<!--
<gazebo reference="${tethernum}_link1">
<mu1 value="1.0"/>
<mu2 value="1.0"/>
<kp  value="10000000.0" />
<kd  value="1.0" />
<fdir1 value="1 0 0"/>
<material>Gazebo/White</material>
<turnGravityOff>false</turnGravityOff>
</gazebo>-->


<!-- Transmission is important to link the joints and the controller -->
<!--
<transmission name="${fb}_${lr}_wheel_joint_trans">
<type>transmission_interface/SimpleTransmission</type>
<joint name="${fb}_${lr}_wheel_joint">
<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
</joint>
<actuator name="${fb}_${lr}_wheel_joint_motor">
<mechanicalReduction>1</mechanicalReduction>
</actuator>
</transmission> -->


</xacro:macro>
</robot>

